#!/usr/bin/env bash

rm -f "${HOME}/antigen.zsh"
rm -rf "${HOME}/.antigen"
rm -f "${HOME}/.git.scmbrc"
rm -f "${HOME}/.scmbrc"
rm -rf "${HOME}/.vim"
rm -f "${HOME}/.vimrc"
rm -f "${HOME}/.tmux.conf"
rm -f "${HOME}/.zshrc"
rm -f "${HOME}/.zshrc.zwc"
